config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'artist_relationships/create'
  get 'artist_relationships/destroy'
  get 'artists/index'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'shows/new'
  get 'shows/import'
  get 'users/new'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/help',        to: 'static_pages#help'
  get '/test',        to: 'static_pages#test'
  get '/login',       to: 'sessions#new'
  get '/signup',      to: 'users#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :agents,              only: [:create, :destroy, :index]
  resources :artists
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :shows,               only: [:new, :create, :index] do
    collection { post :import }
  end
end

app/models/user.rb
  class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  #TODO allow multiple users to have the artist relationship
  has_many :artist_relationships
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  default_scope -> { order(name: :asc) }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\- ]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true

  # Returns true for a standard user, false otherwise.
  def standard_user
    !self.admin
  end


  class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def search search
    users = User.where("name like ?", "%#{search}%")
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  # Example of meta-programming.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgest a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

# Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends an activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

# Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id from relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  #Assign an artist to a user.
  def assign_artist(artist)
    artist_relationships.create(artist_id: artist.id)
  end

  # Returns assigned artists
  #TODO make this method more like 'the rails way'
  def assigned_artists
    artists = Array.new
    self.artist_relationships.each do |relationship|
      artist = Artist.find(relationship.artist_id)
      artists << artist
    end
    return artists
  end

  # Returns the shows assigned to the user for all artists
  def assigned_shows
    shows = Array.new
    self.assigned_artists.each do |artist|
      artist.shows.each do |show|
        shows << show
      end
    end
    # sort shows by date order
    shows.sort_by &:start_date
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      email.downcase!
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy,
                                         :following, :followers]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: :destroy

  def index
    if current_user.standard_user
      redirect_to current_user
    else
      if params[:search]
        temp = User.search params[:search]
        @users = temp.paginate(page: 1)
      else
        @users = User.where(activated: true).paginate(page: params[:page])
      end
    end
  end

  def show
      @user = User.find(params[:id])
      @assigned_artists = current_user.assigned_artists
      redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def smile_for(user)
    smile = 'smile.png'
    image_tag(smile, alt: user.name, class: "gravatar")
  end
end

app/views/users/_admin_user_show.html.erb
<div>
  <h1><%= @user.name %></h1>
  <% if @user != current_user %>
    <h2><%= @user.email %></h2>
  <% end %>
</div>
<h3>Assigned Artists</h3>
<div class="artist_list">
  <ul>
    <% @user.assigned_artists.each do |artist| %>
      <li><%= link_to artist.name, artist %>
        |
        <%= link_to "remove", controller: :artist_relationships,
                              action:     :destroy,
                              artist_id:  artist.id,
                              user_id:    @user.id %>
      </li>
    <% end %>
  </ul>
</div>
<div class="artist_list">
  <h3>Unassigned Artists</h3>
  <ul>
    <% Artist.all.each do |artist| %>
      <% if @user.assigned_artists.exclude? artist %>
        <li>
          <%= artist.name %>
          |
          <%= link_to "add", controller: :artist_relationships,
                             action:     :create,
                             artist_id:  artist.id,
                             user_id:    @user.id %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/_find_user.html.erb
<div class="row">
  <div class="form_margin">
    <span>
      <b>Find user</b>
    </span>
    <%= form_tag users_path, method: 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search], class: 'form-control' %>
      <%= submit_tag 'Search', name: nil, class: "btn btn-primary" %>
    </p>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@find_user) do |f| %>
<%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to smile_for(user), user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                          data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row form_margin">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<h1>Users</h1>

<div class="row">
  <div class="col-md-4 users-wrapper">
    <div>
      <ul class="users">
        <%= render @users %>
      </ul>
      <div class="center">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

  <div class="homepage home-image">
    <div class="homepage-links">
      <span><%= link_to "home", root_path %></span>
      |
      <span><%= link_to "log in", sessions_new_path %></span>
    </div>
    <div class="login-wrapper">
      <div class="login-backdrop">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn label-warning" %>
      <% end %>
  </div>
</div>
</div>





  <!-- <h1>Sign up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div> -->

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <% if current_user.admin %>
    <%= render 'admin_user_show' %>
    <% elsif @user == current_user %>
      <div class="artist_list">
        <h1>Assigned Artists</h1>
        <% @assigned_artists.each do |artist| %>
          <li>
            <%= link_to album_for(artist), artist_path(artist) %>
            <%= link_to artist.name, artist %>
          </li>
        <% end %>
      </div>
    <% end %>