config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'artist_relationships/create'
  get 'artist_relationships/destroy'
  get 'artists/index'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'shows/new'
  get 'shows/import'
  get 'users/new'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/help',        to: 'static_pages#help'
  get '/test',        to: 'static_pages#test'
  get '/login',       to: 'sessions#new'
  get '/signup',      to: 'users#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :agents,              only: [:create, :destroy, :index]
  resources :artists
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :shows,               only: [:new, :create, :index] do
    collection { post :import }
  end
end

app/views/shared/_create_agent_form.html.erb
<div class="row form_margin">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@agent) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label "Agent Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "Agent HubSpot ID" %>
      <%= f.number_field :hubspot_id, class: 'form-control' %>

      <%= f.submit "Add Agent", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_show_upload_form.html.erb
<div class="show_upload_form">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <span><b>Upload hubspot show csv</b></span>
      <br>
      <span class="show_upload_info">
        File must contain 'deal id', 'artist name', 'start date' &
        'deal stage'
      </span>
      <%= form_for(@show, url: import_shows_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <span class="picture">
        <%= f.file_field :csv_file, accept: 'text/csv' %>
      </span>
      <%= f.submit "Upload", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>