config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'artist_relationships/create'
  get 'artist_relationships/destroy'
  get 'artists/index'
  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'shows/new'
  get 'shows/import'
  get 'users/new'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/help',        to: 'static_pages#help'
  get '/test',        to: 'static_pages#test'
  get '/login',       to: 'sessions#new'
  get '/signup',      to: 'users#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :agents,              only: [:create, :destroy, :index]
  resources :artists
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :shows,               only: [:new, :create, :index] do
    collection { post :import }
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by
    <a href="mailto:bkohler4@gmail.com?subject=Auto Agent">Bill Kohler</a>
  </small>
  <nav>
    <ul>
      <% if logged_in? && admin? %>
      <% end %>
      <li><%= link_to "About", about_path %></li>
      <li>
        <a href="mailto:bkohler4@gmail.com?subject=Auto Agent">Contact</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default header_font">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="header-logo">
        <%= link_to 'home icon', root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if params[:controller] == "users" %>
        <%= form_tag users_path, method: 'get', class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Find user" %>
        </div>
        <div class="form-group"><%= submit_tag 'Search', name: nil, class: "btn" %></div>
      <% end %>
    <% else %>
      <%= form_tag artists_path, method: 'get', class: "navbar-form navbar-left" do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Find artist" %>
      </div>
      <div class="form-group"><%= submit_tag 'Search', name: nil, class: "btn" %></div>
    <% end %>
  <% end %>
  <ul class="nav navbar-nav navbar-right">
    <% if admin? %>
      <li><%= link_to "Users", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          Artists
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Artists", artists_path %></li>
          <li><%= link_to "Add Artist", new_artist_path %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Artists", artists_path %></li>
    <% end %>
    <% if admin? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          Shows
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Add Show", new_show_path %></li>
          <li><%= link_to "Assigned Shows", shows_path %></li>
        </ul>
      </li>
    <% end %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Account
        <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
    </li>
  </ul>
</div>
<!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>

app/views/layouts/_logged_out_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse green_header">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_url %>>Auto Agent</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag     'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag  'application',
                            'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway:100" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <% if logged_in? %>
    <body>
      <%=render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </body>
  <% else %>
    <body class="homepage-body-style">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </body>
  <% end %>
</html>